from datetime import datetime

from pydantic import BaseModel


class UserBase(BaseModel):
    # id autogenerated by the database
    # id: int | None = None
    username: str
    email: str | None = None
    full_name: str | None = None
    status: str | None = None
    disabled: bool | None = None
    # created_at: datetime | None = None

class UserCreate(UserBase):
    password: str

class User(UserBase):
    id: int | None = None
    created_at: datetime | datetime = datetime.now()

    class Config:
        from_attributes = True



