pub mod approval_gate;
pub mod ephemeral;
pub mod event_map;
pub mod learning;
pub mod memory_projection;
pub mod memory_scope;
pub mod memory_tools;
pub mod observation;
pub mod policy_middleware;
pub mod policy_violation;
pub mod remote_journal;
pub mod repository;
pub mod retention;
pub mod sandbox_sink;
pub mod skill_events;
pub mod sse_bridge;
pub mod state_projection;
pub mod tracked_fs;

pub use approval_gate::{ApprovalGate, ApprovalOutcome};
// Re-export the traits that ApprovalGate implements, for convenience
pub use arcan_core::runtime::{ApprovalGateHook, ApprovalResolver};
pub use ephemeral::{EphemeralJournal, SessionJournalSelector};
pub use learning::{LearningEntry, LearningMiddleware};
pub use memory_projection::MemoryProjection;
pub use memory_scope::{MemoryEntry, MemoryScopeConfig};
pub use memory_tools::{MemoryCommitTool, MemoryProposeTool, MemoryQueryTool};
pub use observation::{Observation, Observer, Reflector};
pub use policy_middleware::LagoPolicyMiddleware;
pub use remote_journal::RemoteLagoJournal;
pub use repository::LagoSessionRepository;
pub use retention::{FreeTierJournal, LagoPolicyConfig, ProTierJournal};
pub use sandbox_sink::LagoSandboxEventSink;
pub use skill_events::SkillProjection;
pub use sse_bridge::{SseBridge, select_format};
pub use state_projection::AppStateProjection;
pub use tracked_fs::{LagoTrackedFs, run_event_writer};
